all: m01ex06

m01ex06: m01ex06.o
	@echo "Making executable."
	gcc m01ex06.o -o m01ex06

m01ex06.o: m01ex06.c
	@echo "Compiling file."
	gcc -c m01ex06.c

clean:
	@echo "Removing files."
	rm m01ex06.o m01ex06