all: m01ex02

m01ex02: m01ex02.o
	@echo "Making executable."
	gcc m01ex02.o -o m01ex02

m01ex02.o: m01ex02.c
	@echo "Compiling m01ex02 file."
	gcc -c m01ex02.c 

clean: 
	@echo "Removing Files."
	rm m01ex02.o m01ex02