all: m01ex04

m01ex04: m01ex04.o
	@echo "Creating executable."
	gcc m01ex04.o -o m01ex04

m01ex04.o: m01ex04.c
	@echo "Compiling file."
	gcc -c m01ex04.c

clean: 
	@echo "Removing files."
	rm m01ex04.o m01ex04