all: m01ex10

m01ex10: m01ex10.o
	@echo "Creating executable."
	gcc m01ex10.o -o m01ex10

m01ex10.o: m01ex10.c
	@echo "Compiling files."
	gcc -c m01ex10.c

clean:
	@echo "Removing files."
	rm m01ex10.o m01ex10