all: m01ex07

m01ex07: m01ex07.o
	@echo "Creating executable."
	gcc m01ex07.o -o m01ex07

m01ex07.o: m01ex07.c
	@echo "Compiling files."
	gcc -c m01ex07.c

clean:
	@echo "Removing files."
	rm m01ex07.o m01ex07