all: m01ex09

m01ex09: m01ex09.o
	@echo "Creating executable."
	gcc m01ex09.o -o m01ex09

m01ex09.o: m01ex09.c
	@echo "Compiling files."
	gcc -c m01ex09.c

clean:
	@echo "Removing files."
	rm m01ex09.o m01ex09